COOLDOWN_AFTER_DETECTION: 60
CROP_HEIGHT: 650
CROP_WIDTH: 800
EPOCHS: 25
IDENTIFICATION: true
MASK1_HIGH:
- 175
- 130
- 0
MASK1_LOW:
- 180
- 255
- 255
MASK2_HIGH:
- 0
- 100
- 0
MASK2_LOW:
- 20
- 255
- 255
OBJECTS: 14
PX_TO_MM: 1.2769098896214846
ROBOT_IN_POS:
  THRESHOLD: 50
  X: 225
  Y: 96
ROBOT_IN_POS_L:
  THRESHOLD: 50
  X: 298
  Y: 319
WAIT_TIME: 2
